### PR TITLE
adding dependabot for GHA

### PR DESCRIPTION
**Pull request by makrsmark**
running GHA when script or workflow changes via PR

### CODE REVIEW

**Comment by makrsmark** [comment]
I wouldn't approve yet- i was expecting the workflows to run in this PR and i can't make this a draft PR.

**Comment by makrsmark** [comment]
probably want to only commit if it's the master branch... will try to update later

**Comment by kevinelliott** [comment]
> will try to update later

Sounds good.

**Comment by kevinelliott** [comment]
Thanks @makrsmark ! Happy holidays. The continued improvements very appreciated.

**Pull request merged**
