### PR TITLE
Ground station details as of 3/18/24

### PR DESCRIPTION
**Pull request by fredclausen**
This may conflict with #36. Not sure.

### CODE REVIEW

**Review by kevinelliott — APPROVED** [review]
Fantastic, thanks @fredclausen !

**Comment by kevinelliott** [comment]
@fredclausen feel free to merge at your convenience

**Comment by fredclausen** [comment]
> @fredclausen feel free to merge at your convenience

I don’t have write access, otherwise I would :)

**Comment by kevinelliott** [comment]
> > @fredclausen feel free to merge at your convenience
> 
> I don’t have write access, otherwise I would :)

Invited you into the repo with elevated privileges.

**Pull request merged**
