### PR TITLE
Update KATW, KBTL, KGRB, KOSC, KSBN, and KUGN details

### PR DESCRIPTION
**Pull request by Phaeton**
Update KOSC details. In incorrectly references the decommissioned AFB.
https://en.wikipedia.org/wiki/Oscoda%E2%80%93Wurtsmith_Airport

Update KUGN details. It incorrectly references old name.
https://en.wikipedia.org/wiki/Waukegan_National_Airport

Update KBTL details. It incorrectly references old name.
https://en.wikipedia.org/wiki/W._K._Kellogg_Airport

Update KGRB details. Had incomplete name.
https://en.wikipedia.org/wiki/Green_Bay%E2%80%93Austin_Straubel_International_Airport

Update KATW details. Had incorrect name.
https://en.wikipedia.org/wiki/Appleton_International_Airport

Update KSBN details. Had incorrect name.
https://en.wikipedia.org/wiki/South_Bend_International_Airport

### CODE REVIEW

**Comment by fredclausen** [comment]
Just as an FYI, the "master source" of this data is from [groups.io](https://acars-vdl2.groups.io/g/main). It may be worth suggesting those changes you have there so they end up in the dataset and don't get overwritten later.

**Comment by kevinelliott** [comment]
@Phaeton 

First of all, sorry for the delay here. Part of this is because of focuses on other areas, but also because I was trying to think of how to handle these specific additions. And thank you so very much for the thoughtful contribution and the time spent.

As @fredclausen mentioned, we are pulling down the VDL ground stations CSV from the acars-vdl2 groups.io group. We put them here in this repository to make it easy for various projects (including Airframes and ACARS Hub) to grab the raw CSV programmatically using the GitHub raw url. Updating this file ends up updating the various projects as they pull things in.

So your contributions here are fantastic. But, as Fred also suggested, I would think contributing these changes upstream to the groups.io group would be best.

However, if for some reason, you wish to override their file, we could add the capability to do so. Just let us know which way you'd prefer to proceed.

**Comment by Phaeton** [comment]
Thanks for the info on the upstream. I'm currently waiting to be approved into the group. :hourglass_flowing_sand:

**Comment by Phaeton** [comment]
Looks like half of them made it in, not sure why not on the rest, but will close this for now. The fixed ones will be picked up on Fred's next update.

**Pull request closed without merging**
